modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="so_below"
version="1.0.0"
displayName="So Below"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="tobyd, MCreator"

[[dependencies.so_below]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




